### ISSUE TITLE
已经过时的库

### ISSUE THREAD

**Issue by xm0625** [dovejb/quicktag#1]
fork完改吧改吧到go 1.18， 发现嵌套场景不好使啊。。。弃，mark一下

**Comment by xm0625** [comment]
type M3u8UrlTaskInfo struct {
		Url string
		Method string
		Body string // post method valid
		HeaderMap map[string]string
		ThreadNum int
		SavePath string // 相对路径 最终路径会拼接上环境变量

		Status int // 下载状态 0:"waiting" 1:"downloading" -1:"failed"
		PercentNum int
		TotalFile int
		DownloadedFile int
	}

	resultList := make([]M3u8UrlTaskInfo, 5, 5)

**Comment by xm0625** [comment]
看样子是对这种List里面套struct的场景没有支持？

**Comment by dovejb** [comment]
这个是之前在tx为了晋升写的技术总结文章搞的demo版本，各种细节没打磨过，后来也没咋更新了。。
在tx使用的那个版本功能更全面一点。
不过我不建议用这个机制了，我记得这里会struct_of一个虚拟类型, 这个东西在循环引用时有时会把内存搞爆, 要考虑的东西太多.

**Comment by xm0625** [comment]
哈哈哈 我就说。。。
不过那个tx的技术文章我看了，可以体现思考很深入，晋升应该是稳的。

刚接触golang，研究了一圈发现好像只能tag方式搞定json转换后的首字母大写的问题

**Comment by dovejb** [comment]
是的, 后来是晋升了. 再然后也离职了, 然后部门项目都解散了, 然后有的人被辞更多人走了, 发生了很多很多事情.
听说有的IDE能自动加这些tag, goland什么的.

**Comment by xm0625** [comment]
当行业处于上升期的时候，一切都是向好的，当平衡被打破的时候，唯一的不变就是变化了。。。

我来研究研究，现在还是用的IDEA加go的插件，本来只想着go能打垮平台静态链接包，分发上比py、nodejs强不少，内存管理也好一些，可以跑在arm等路由器设备上，想写个小玩意的。结果发现开发效率还挺高，有gomod包管理之后`几乎`赶上py了
